# -------------------
#   General
# -------------------
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
  # -------------------
  #   Python-specific
  # -------------------
  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
  # Format and lint
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/myint/docformatter # Format Python doc strings
    rev: v1.7.5
    hooks:
      - id: docformatter
    args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]
  # ------------------
  #   Other formatters
  # ------------------
  # Format YAML files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"
  # Format bash files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  # ------------------
  #   Git-specific
  # ------------------
  # Using this npm package: https://commitlint.js.org/#/
  # Adapted into pre-commit framework
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: ./config/commitlint.sh
        language: system
        pass_filenames: false
  # -------------------
  #      Security
  # -------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["--exclude", "tests"]
