# -------------------
#   General
# -------------------
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
  # -------------------
  #       Python
  # -------------------
  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
  # Format and lint
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [setuptools]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        args: [--config, pyproject.toml]
  # Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["--exclude", "tests"]
  # -------------------
  #     Terraform
  # -------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - "--args=--lockfile=false"
      - id: terraform_tflint
        args:
          - "--args=--no-module"
          - "--args=--only=terraform_comment_syntax"
          - "--args=--only=terraform_deprecated_index"
          - "--args=--only=terraform_deprecated_interpolation"
          - "--args=--only=terraform_documented_outputs"
          - "--args=--only=terraform_documented_variables"
          - "--args=--only=terraform_module_pinned_source"
          - "--args=--only=terraform_module_version"
          - "--args=--only=terraform_naming_convention"
          - "--args=--only=terraform_required_providers"
          - "--args=--only=terraform_required_version"
          - "--args=--only=terraform_typed_variables"
          - "--args=--only=terraform_unused_declarations"
          - "--args=--only=terraform_unused_required_providers"
          - "--args=--only=terraform_workspace_remote"
  # ------------------
  #       Bash
  # ------------------
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  # ------------------
  #       YAML
  # ------------------
  # Format YAML files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"
  # ------------------
  #      Git
  # ------------------
  # Use regex to enforce conventional commits
  # See https://www.conventionalcommits.org/en/v1.0.0/
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: ./config/commitlint.sh
        language: system
        pass_filenames: false
