name: CI

on:
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/ci_main.yml"

env:
  PYTHONPATH: .

jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set env vars
        run: |
          echo "BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's|^refs/heads/||')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "${{ env.BRANCH_NAME }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Define preferred Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies using Poetry
        run: |
          rm poetry.lock
          poetry lock --no-update
          poetry install

      - name: Run tests status check
        run: |
          poetry run pytest tests
